### ISSUE TITLE
Included script doesn't seem to work at all

### ISSUE THREAD

**Issue by mothdotmonster** [Mynotaurus/Yingmotes#1]
Upon trying to run the included script, it errors out at the first image, with the following output:

```
Finding SVGs...
Making new directory...
Changing ying_sunglasses_blep.svg to orange...
Saving vector orange/svg/ying_sunglasses_blep.svg...
Saving image orange/png128/ying_sunglasses_blep.png...
Traceback (most recent call last):
  File "/home/chesapeake/Downloads/Yingmotes-main/./generate.py", line 122, in <module>
    convert_with_inkscape(pal+"/svg/"+vectorfile, i, pal+"/png"+str(i)+"/"+vectorfile.replace(".svg",".png"))
  File "/home/chesapeake/Downloads/Yingmotes-main/./generate.py", line 86, in convert_with_inkscape
    print(subprocess.run(args)) #if this says "returncode=0" thats good! if its not a zero thats bad, smths going wrong
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'inkscape --without-gui orange/svg/ying_sunglasses_blep.svg --export-area-page -w 128 -h 128 --export-filename=orange/png128/ying_sunglasses_blep.png'
```

I'm running under Arch Linux; what did you write this script using?

**Comment by Mynotaurus** [comment]
hrm rats, i wrote it on windows, what that line does is just run the command thats stored in `args` on the command line

python doesnt seem to say anywhere that its a platform-specific function? so i wonder if its a different command to launch the program on linux

just found a way to make exporting much more efficient so ill push an update later today to see if i can make it work on all platforms at the same time

**Comment by Mynotaurus** [comment]
found it, added a `shell=True` term which shouuuld improve compatibility, try the new version?

**Comment by mothdotmonster** [comment]
it worked!
![thio_heart](https://github.com/Mynotaurus/Yingmotes/assets/82258270/8d73ba9d-7e14-495c-9b64-b80455392f94)
